# 389. Find the Difference
#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        dic_s={}
        dic_t={}
        for i in s:
            if i not in dic_s:
                dic_s[i]=1
            else:
                dic_s[i]+=1
        for i in t:
            if i not in dic_t:
                dic_t[i]=1
            else:
                dic_t[i]+=1

        for i in t:
            if i not in s:
                return i
            else:
                if dic_s[i]-dic_t[i]!=0:
                    return i
